In [1]:
import pandas as pd
df = pd.read_excel('data.xls')

In [2]:
df_list = df.dropna().values

In [3]:
df_list

array([['088/01/13', '104 台北二  ', 'T5 西瓜 黃肉 ', 5.0, 60.0, 3400.0],
       ['088/01/15', '104 台北二  ', 'T5 西瓜 黃肉 ', 12.0, 90.0, 18101.0],
       ['088/01/17', '104 台北二  ', 'T5 西瓜 黃肉 ', 21.8, 634.0,
        12922.800000000001],
       ...,
       ['108/12/25', '104 台北二  ', 'T5 西瓜 黃肉 ', 10.6, 1621.0,
        25490.399999999998],
       ['108/12/26', '104 台北二  ', 'T5 西瓜 黃肉 ', 9.1, 1030.0,
        13081.199999999999],
       ['108/12/29', '104 台北二  ', 'T5 西瓜 黃肉 ', 9.5, 653.0, 10968.0]],
      dtype=object)

In [4]:
year_list=[]
for i in range(88,100):
    year_list.append('0'+str(i))
for i in range(100,109):
    year_list.append(str(i))
month_list = []
for i in range(1,10):
    month_list.append('0'+str(i))
for i in range(10,13):
    month_list.append(str(i))

In [5]:
print(year_list)
print(month_list)

['088', '089', '090', '091', '092', '093', '094', '095', '096', '097', '098', '099', '100', '101', '102', '103', '104', '105', '106', '107', '108']
['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']

In [6]:
def avg(x):
    return sum(x)/len(x)

In [7]:
x = ['104','088']
for i in x:
    if i[0] == '0':
        y = i[1:]
    else:
        y = i

In [8]:
def ch_to_west(x):
    if x[0] == '0':
        y = x[1:]
    else:
        y = x
    return str(int(y)+1911)

In [9]:
for year in year_list:
    print(year)

088
089
090
091
092
093
094
095
096
097
098
099
100
101
102
103
104
105
106
107
108

In [10]:
new_df = []
avg_price = []
avg_vol = []
for year in year_list:
    for month in month_list:
        price = []
        vol=[]
        for i in df_list:
            date = i[0].split('/')
            if date[1] == month and date[0] ==year:
                price.append(i[3])
                vol.append(i[4])
        if len(price)== 0:
            price.append(avg_price[-1])
        if len(vol) == 0:
            vol.append(avg_vol[-1])
        avg_price.append(avg(price))
        avg_vol.append(avg(vol))
        #ew_df.append([year+'/'+month,year,month,round(avg(price),1),round(avg(vol),1)])
        new_df.append([ch_to_west(year)+'-'+month,ch_to_west(year),month,round(avg(price),1),round(avg(vol),1)])
new_df

[['1999-01', '1999', '01', 20.3, 230.3],
 ['1999-02', '1999', '02', 27.7, 2248.7],
 ['1999-03', '1999', '03', 15.8, 18235.1],
 ['1999-04', '1999', '04', 11.2, 26201.8],
 ['1999-05', '1999', '05', 8.6, 27782.8],
 ['1999-06', '1999', '06', 9.3, 31282.5],
 ['1999-07', '1999', '07', 9.3, 21000.6],
 ['1999-08', '1999', '08', 15.1, 10110.7],
 ['1999-09', '1999', '09', 17.0, 10218.2],
 ['1999-10', '1999', '10', 14.6, 3904.2],
 ['1999-11', '1999', '11', 12.6, 3044.0],
 ['1999-12', '1999', '12', 13.5, 1041.3],
 ['2000-01', '2000', '01', 17.2, 831.3],
 ['2000-02', '2000', '02', 14.1, 3084.5],
 ['2000-03', '2000', '03', 18.6, 3697.6],
 ['2000-04', '2000', '04', 16.9, 20886.0],
 ['2000-05', '2000', '05', 12.4, 27153.0],
 ['2000-06', '2000', '06', 6.4, 40697.7],
 ['2000-07', '2000', '07', 10.2, 20844.9],
 ['2000-08', '2000', '08', 12.3, 11012.4],
 ['2000-09', '2000', '09', 12.5, 9826.8],
 ['2000-10', '2000', '10', 18.9, 2823.4],
 ['2000-11', '2000', '11', 13.5, 2265.5],
 ['2000-12', '2000', '12', 19.1, 264.7],
 ['2001-01', '2001', '01', 18.8, 607.4],
 ['2001-02', '2001', '02', 17.5, 4559.5],
 ['2001-03', '2001', '03', 11.9, 11706.7],
 ['2001-04', '2001', '04', 6.7, 32992.0],
 ['2001-05', '2001', '05', 9.0, 20068.0],
 ['2001-06', '2001', '06', 12.1, 19941.4],
 ['2001-07', '2001', '07', 11.6, 16509.2],
 ['2001-08', '2001', '08', 15.6, 12757.6],
 ['2001-09', '2001', '09', 10.8, 10386.1],
 ['2001-10', '2001', '10', 12.2, 1090.3],
 ['2001-11', '2001', '11', 12.5, 1645.5],
 ['2001-12', '2001', '12', 9.0, 863.7],
 ['2002-01', '2002', '01', 6.2, 564.2],
 ['2002-02', '2002', '02', 9.0, 2255.8],
 ['2002-03', '2002', '03', 13.2, 13555.7],
 ['2002-04', '2002', '04', 9.3, 18712.6],
 ['2002-05', '2002', '05', 7.1, 26320.3],
 ['2002-06', '2002', '06', 10.2, 20719.0],
 ['2002-07', '2002', '07', 12.2, 8663.5],
 ['2002-08', '2002', '08', 7.8, 16486.0],
 ['2002-09', '2002', '09', 7.4, 6717.7],
 ['2002-10', '2002', '10', 14.4, 2864.9],
 ['2002-11', '2002', '11', 14.1, 1717.9],
 ['2002-12', '2002', '12', 7.6, 155.8],
 ['2003-01', '2003', '01', 10.1, 367.0],
 ['2003-02', '2003', '02', 15.3, 2838.1],
 ['2003-03', '2003', '03', 13.2, 9950.0],
 ['2003-04', '2003', '04', 11.2, 11269.2],
 ['2003-05', '2003', '05', 10.6, 12374.0],
 ['2003-06', '2003', '06', 7.8, 13329.4],
 ['2003-07', '2003', '07', 13.1, 9056.1],
 ['2003-08', '2003', '08', 6.8, 18217.1],
 ['2003-09', '2003', '09', 10.6, 7692.1],
 ['2003-10', '2003', '10', 11.4, 3751.9],
 ['2003-11', '2003', '11', 11.4, 2243.0],
 ['2003-12', '2003', '12', 10.4, 672.0],
 ['2004-01', '2004', '01', 3.7, 764.5],
 ['2004-02', '2004', '02', 27.0, 2395.3],
 ['2004-03', '2004', '03', 21.2, 4042.1],
 ['2004-04', '2004', '04', 8.9, 16789.8],
 ['2004-05', '2004', '05', 7.7, 17554.8],
 ['2004-06', '2004', '06', 8.8, 15250.2],
 ['2004-07', '2004', '07', 14.5, 7967.1],
 ['2004-08', '2004', '08', 17.8, 8603.0],
 ['2004-09', '2004', '09', 6.4, 13027.3],
 ['2004-10', '2004', '10', 9.0, 3637.6],
 ['2004-11', '2004', '11', 7.2, 5255.8],
 ['2004-12', '2004', '12', 10.8, 898.5],
 ['2005-01', '2005', '01', 10.8, 898.5],
 ['2005-02', '2005', '02', 22.9, 546.6],
 ['2005-03', '2005', '03', 14.5, 2514.6],
 ['2005-04', '2005', '04', 24.1, 2657.9],
 ['2005-05', '2005', '05', 13.8, 11637.9],
 ['2005-06', '2005', '06', 16.1, 8107.4],
 ['2005-07', '2005', '07', 25.6, 6337.9],
 ['2005-08', '2005', '08', 22.2, 2593.5],
 ['2005-09', '2005', '09', 16.2, 3094.8],
 ['2005-10', '2005', '10', 19.2, 3539.0],
 ['2005-11', '2005', '11', 16.5, 3874.9],
 ['2005-12', '2005', '12', 10.7, 720.8],
 ['2006-01', '2006', '01', 19.1, 569.0],
 ['2006-02', '2006', '02', 6.5, 119.0],
 ['2006-03', '2006', '03', 16.9, 4440.0],
 ['2006-04', '2006', '04', 14.3, 5503.1],
 ['2006-05', '2006', '05', 10.7, 13249.4],
 ['2006-06', '2006', '06', 14.5, 7811.1],
 ['2006-07', '2006', '07', 16.8, 9860.7],
 ['2006-08', '2006', '08', 13.1, 14548.4],
 ['2006-09', '2006', '09', 13.4, 12865.9],
 ['2006-10', '2006', '10', 11.7, 7877.5],
 ['2006-11', '2006', '11', 10.8, 4304.7],
 ['2006-12', '2006', '12', 7.7, 137.0],
 ['2007-01', '2007', '01', 9.4, 360.6],
 ['2007-02', '2007', '02', 10.7, 1067.3],
 ['2007-03', '2007', '03', 12.5, 11570.8],
 ['2007-04', '2007', '04', 10.6, 20102.6],
 ['2007-05', '2007', '05', 11.3, 16160.7],
 ['2007-06', '2007', '06', 8.9, 15098.4],
 ['2007-07', '2007', '07', 10.5, 20654.6],
 ['2007-08', '2007', '08', 9.4, 22768.1],
 ['2007-09', '2007', '09', 15.8, 2285.6],
 ['2007-10', '2007', '10', 12.3, 1312.4],
 ['2007-11', '2007', '11', 9.5, 1263.4],
 ['2007-12', '2007', '12', 7.6, 1729.4],
 ['2008-01', '2008', '01', 12.4, 89.0],
 ['2008-02', '2008', '02', 16.2, 776.4],
 ['2008-03', '2008', '03', 15.0, 2106.5],
 ['2008-04', '2008', '04', 15.9, 11836.5],
 ['2008-05', '2008', '05', 10.3, 10997.3],
 ['2008-06', '2008', '06', 11.5, 16514.7],
 ['2008-07', '2008', '07', 18.9, 9278.8],
 ['2008-08', '2008', '08', 20.2, 4492.7],
 ['2008-09', '2008', '09', 13.4, 7584.1],
 ['2008-10', '2008', '10', 17.6, 3692.9],
 ['2008-11', '2008', '11', 13.6, 3763.7],
 ['2008-12', '2008', '12', 11.2, 1883.9],
 ['2009-01', '2009', '01', 6.1, 618.8],
 ['2009-02', '2009', '02', 21.9, 2292.6],
 ['2009-03', '2009', '03', 14.5, 8075.4],
 ['2009-04', '2009', '04', 8.0, 16616.3],
 ['2009-05', '2009', '05', 14.0, 13574.4],
 ['2009-06', '2009', '06', 10.6, 16965.8],
 ['2009-07', '2009', '07', 13.9, 15140.2],
 ['2009-08', '2009', '08', 15.8, 6017.8],
 ['2009-09', '2009', '09', 30.6, 1164.1],
 ['2009-10', '2009', '10', 13.6, 7666.4],
 ['2009-11', '2009', '11', 10.0, 9247.5],
 ['2009-12', '2009', '12', 12.0, 3076.7],
 ['2010-01', '2010', '01', 12.0, 3076.7],
 ['2010-02', '2010', '02', 19.1, 4515.0],
 ['2010-03', '2010', '03', 18.0, 7309.4],
 ['2010-04', '2010', '04', 12.9, 13768.1],
 ['2010-05', '2010', '05', 11.3, 8346.8],
 ['2010-06', '2010', '06', 7.0, 17491.1],
 ['2010-07', '2010', '07', 14.3, 16850.8],
 ['2010-08', '2010', '08', 13.5, 20401.1],
 ['2010-09', '2010', '09', 11.3, 9740.7],
 ['2010-10', '2010', '10', 22.4, 1689.1],
 ['2010-11', '2010', '11', 14.0, 3351.6],
 ['2010-12', '2010', '12', 15.9, 629.2],
 ['2011-01', '2011', '01', 7.4, 594.4],
 ['2011-02', '2011', '02', 7.3, 331.0],
 ['2011-03', '2011', '03', 18.3, 5025.5],
 ['2011-04', '2011', '04', 14.3, 19399.2],
 ['2011-05', '2011', '05', 13.8, 18156.8],
 ['2011-06', '2011', '06', 15.0, 19423.4],
 ['2011-07', '2011', '07', 13.0, 21109.6],
 ['2011-08', '2011', '08', 12.6, 21348.7],
 ['2011-09', '2011', '09', 15.7, 7708.3],
 ['2011-10', '2011', '10', 12.8, 6265.0],
 ['2011-11', '2011', '11', 11.0, 3979.3],
 ['2011-12', '2011', '12', 11.0, 3979.3],
 ['2012-01', '2012', '01', 8.4, 256.5],
 ['2012-02', '2012', '02', 8.4, 256.5],
 ['2012-03', '2012', '03', 19.1, 5203.4],
 ['2012-04', '2012', '04', 13.8, 18445.4],
 ['2012-05', '2012', '05', 12.2, 19121.7],
 ['2012-06', '2012', '06', 12.7, 17567.2],
 ['2012-07', '2012', '07', 31.9, 8993.1],
 ['2012-08', '2012', '08', 17.0, 14215.4],
 ['2012-09', '2012', '09', 19.2, 8451.5],
 ['2012-10', '2012', '10', 13.2, 7919.8],
 ['2012-11', '2012', '11', 14.6, 6532.2],
 ['2012-12', '2012', '12', 14.0, 1213.5],
 ['2013-01', '2013', '01', 8.5, 49.7],
 ['2013-02', '2013', '02', 19.4, 2219.1],
 ['2013-03', '2013', '03', 15.6, 8673.3],
 ['2013-04', '2013', '04', 9.1, 12401.2],
 ['2013-05', '2013', '05', 12.6, 11456.9],
 ['2013-06', '2013', '06', 18.7, 15055.0],
 ['2013-07', '2013', '07', 11.7, 21184.1],
 ['2013-08', '2013', '08', 17.0, 17171.8],
 ['2013-09', '2013', '09', 22.4, 6033.7],
 ['2013-10', '2013', '10', 18.2, 7355.1],
 ['2013-11', '2013', '11', 11.1, 4187.4],
 ['2013-12', '2013', '12', 11.4, 1235.6],
 ['2014-01', '2014', '01', 12.0, 144.0],
 ['2014-02', '2014', '02', 24.6, 444.0],
 ['2014-03', '2014', '03', 18.9, 5013.5],
 ['2014-04', '2014', '04', 15.9, 16950.1],
 ['2014-05', '2014', '05', 13.5, 12580.7],
 ['2014-06', '2014', '06', 12.0, 10160.8],
 ['2014-07', '2014', '07', 13.5, 19492.0],
 ['2014-08', '2014', '08', 16.1, 17326.8],
 ['2014-09', '2014', '09', 19.2, 11914.4],
 ['2014-10', '2014', '10', 17.7, 4673.4],
 ['2014-11', '2014', '11', 15.8, 2260.3],
 ['2014-12', '2014', '12', 13.0, 949.4],
 ['2015-01', '2015', '01', 11.8, 163.6],
 ['2015-02', '2015', '02', 22.0, 99.0],
 ['2015-03', '2015', '03', 12.7, 8660.6],
 ['2015-04', '2015', '04', 11.1, 20036.3],
 ['2015-05', '2015', '05', 13.3, 14946.4],
 ['2015-06', '2015', '06', 16.3, 14622.2],
 ['2015-07', '2015', '07', 11.2, 27651.4],
 ['2015-08', '2015', '08', 10.3, 30799.0],
 ['2015-09', '2015', '09', 23.0, 3426.1],
 ['2015-10', '2015', '10', 15.4, 5130.4],
 ['2015-11', '2015', '11', 12.4, 3911.4],
 ['2015-12', '2015', '12', 11.0, 1135.7],
 ['2016-01', '2016', '01', 7.5, 982.5],
 ['2016-02', '2016', '02', 17.3, 972.0],
 ['2016-03', '2016', '03', 16.6, 5449.9],
 ['2016-04', '2016', '04', 22.4, 9563.7],
 ['2016-05', '2016', '05', 26.3, 14663.3],
 ['2016-06', '2016', '06', 15.1, 21902.0],
 ['2016-07', '2016', '07', 26.5, 14199.0],
 ['2016-08', '2016', '08', 22.8, 24319.6],
 ['2016-09', '2016', '09', 13.9, 13089.0],
 ['2016-10', '2016', '10', 15.6, 1695.3],
 ['2016-11', '2016', '11', 25.2, 512.7],
 ['2016-12', '2016', '12', 18.3, 1546.2],
 ['2017-01', '2017', '01', 19.8, 360.2],
 ['2017-02', '2017', '02', 14.1, 6585.4],
 ['2017-03', '2017', '03', 12.8, 5739.9],
 ['2017-04', '2017', '04', 13.5, 11709.0],
 ['2017-05', '2017', '05', 17.8, 9365.4],
 ['2017-06', '2017', '06', 11.7, 14625.3],
 ['2017-07', '2017', '07', 20.0, 14697.1],
 ['2017-08', '2017', '08', 12.9, 29048.7],
 ['2017-09', '2017', '09', 16.6, 15533.2],
 ['2017-10', '2017', '10', 13.3, 11279.6],
 ['2017-11', '2017', '11', 14.0, 2430.6],
 ['2017-12', '2017', '12', 10.6, 1268.6],
 ['2018-01', '2018', '01', 10.6, 1268.6],
 ['2018-02', '2018', '02', 10.6, 1268.6],
 ['2018-03', '2018', '03', 23.3, 8831.8],
 ['2018-04', '2018', '04', 10.8, 38365.0],
 ['2018-05', '2018', '05', 12.2, 19975.7],
 ['2018-06', '2018', '06', 13.8, 14960.2],
 ['2018-07', '2018', '07', 17.6, 14343.2],
 ['2018-08', '2018', '08', 12.7, 21482.3],
 ['2018-09', '2018', '09', 11.5, 10128.6],
 ['2018-10', '2018', '10', 12.7, 4805.1],
 ['2018-11', '2018', '11', 8.5, 4665.5],
 ['2018-12', '2018', '12', 8.7, 821.4],
 ['2019-01', '2019', '01', 8.7, 821.4],
 ['2019-02', '2019', '02', 11.3, 5553.3],
 ['2019-03', '2019', '03', 8.9, 9625.9],
 ['2019-04', '2019', '04', 14.9, 13723.7],
 ['2019-05', '2019', '05', 15.3, 12717.2],
 ['2019-06', '2019', '06', 16.1, 11395.4],
 ['2019-07', '2019', '07', 14.4, 17597.9],
 ['2019-08', '2019', '08', 14.8, 15618.3],
 ['2019-09', '2019', '09', 22.8, 3924.3],
 ['2019-10', '2019', '10', 16.9, 8380.7],
 ['2019-11', '2019', '11', 15.1, 981.7],
 ['2019-12', '2019', '12', 14.3, 1166.3]]

In [11]:
df_new = pd.DataFrame(new_df,columns=['date','year','month','price','volumn'])
df_new.to_csv('month_data.csv',encoding='utf-8-sig')