In [5]:
import pandas as pd
df = pd.read_csv('3.final.csv',encoding='utf-8')

In [9]:
df[df['產品名'] == '西瓜']

,日期,產品名,平均價格,上價,中價,下價,交易量,月前氣溫,月前最低氣溫,月前相對溼度,...,月前五日移動平均風速,月前十日移動平均風速,月前二十日移動平均風速,月前五十日移動平均風速,月前百日移動平均風速,月前五日移動平均降水,月前十日移動平均降水,月前二十日移動平均降水,月前五十日移動平均降水,月前百日移動平均降水
4881,2015/01/01,西瓜,10.0,10.0,10.0,10.0,310.0,16.2,13.8,72.0,...,3.60,3.60,3.60,3.60,3.60,2.00,2.00,2.00,2.00,2.00
4882,2015/01/02,西瓜,10.3,13.0,9.8,9.0,80.0,21.4,17.7,69.0,...,2.40,2.40,2.40,2.40,2.40,2.00,2.00,2.00,2.00,2.00
4883,2015/01/03,西瓜,10.0,10.0,10.0,10.0,1370.0,14.8,12.6,78.0,...,2.10,2.10,2.10,2.10,2.10,27.00,27.00,27.00,27.00,27.00
4884,2015/01/04,西瓜,9.0,9.0,9.0,9.0,140.0,14.6,13.7,61.0,...,3.40,3.40,3.40,3.40,3.40,0.00,0.00,0.00,0.00,0.00
4885,2015/01/07,西瓜,8.0,8.0,8.0,8.0,307.0,17.2,16.3,82.0,...,3.50,3.50,3.50,3.50,3.50,5.50,5.50,5.50,5.50,5.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6305,2020/05/27,西瓜,10.2,14.0,10.7,5.0,6588.0,22.3,21.0,76.0,...,3.18,2.50,2.45,2.51,2.42,5.86,2.93,2.99,5.48,3.41
6306,2020/05/28,西瓜,13.3,14.0,14.0,10.5,12810.0,24.0,20.0,59.0,...,3.44,2.66,2.50,2.48,2.42,5.30,3.07,2.98,5.50,3.42
6307,2020/05/29,西瓜,11.7,14.0,11.5,10.0,23190.0,25.9,21.7,57.0,...,3.48,2.99,2.59,2.54,2.44,5.04,3.07,2.92,5.50,3.42
6308,2020/05/30,西瓜,11.5,14.0,12.2,7.1,12551.0,26.7,20.7,58.0,...,3.16,3.11,2.56,2.56,2.45,1.82,3.07,2.63,5.50,3.42
6309,2020/05/31,西瓜,9.5,14.0,9.6,4.8,5987.0,27.1,22.8,58.0,...,2.64,3.14,2.56,2.49,2.43,0.32,3.07,2.53,5.50,3.42