In [32]:
import pandas as pd
df = pd.read_excel('data.xls')

In [33]:
df_list = df.dropna().values

In [63]:
df

           日　　期       市　　場       產　　品  平均價(元/公斤)  交易量(公斤)    Unnamed: 5
0     088/01/02  104 台北二    T5 西瓜 黃肉        20.0    170.0           NaN
1     088/01/03  104 台北二    T5 西瓜 黃肉        23.0    787.0           NaN
2     088/01/10  104 台北二    T5 西瓜 黃肉        17.8    726.0           NaN
3     088/01/11  104 台北二    T5 西瓜 黃肉        15.2    752.0           NaN
4     088/01/13  104 台北二    T5 西瓜 黃肉         5.0     60.0  3.400000e+03
...         ...        ...        ...        ...      ...           ...
5156        NaN        NaN        NaN        NaN      NaN  1.465890e+04
5157        NaN        NaN        NaN        NaN      NaN  1.718260e+04
5158        NaN        NaN        NaN        NaN      NaN  9.373000e+03
5159        NaN        NaN        NaN        NaN      NaN  6.203500e+03
5160        NaN        NaN        NaN        NaN      NaN  6.992995e+08

[5161 rows x 6 columns]

In [26]:
year_list=[]
for i in range(88,100):
    year_list.append('0'+str(i))
for i in range(100,109):
    year_list.append(str(i))
month_list = []
for i in range(1,10):
    month_list.append('0'+str(i))
for i in range(10,13):
    month_list.append(str(i))
year_month = []
for year in year_list:
    for month in month_list:
        year_month.append(str(year)

In [27]:
print(year_list)
print(month_list)

['088', '089', '090', '091', '092', '093', '094', '095', '096', '097', '098', '099', '100', '101', '102', '103', '104', '105', '106', '107', '108']
['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']

In [35]:
def avg(x):
    return sum(x)/len(x)

In [68]:
new_df = []
avg_price = []
avg_vol = []
for year in year_list:
    for month in month_list:
        price = []
        vol=[]
        for i in df_list:
            date = i[0].split('/')
            if date[1] == month and date[0] ==year:
                price.append(i[3])
                vol.append(i[4])
        if len(price)== 0:
            price.append(avg_price[-1])
        if len(vol) == 0:
            vol.append(avg_vol[-1])
        avg_price.append(avg(price))
        avg_vol.append(avg(vol))
        new_df.append([year+'/'+month,year,month,round(avg(price),1),round(avg(vol),1)])
new_df

[['088/01', '088', '01', 20.3, 230.3],
 ['088/02', '088', '02', 27.7, 2248.7],
 ['088/03', '088', '03', 15.8, 18235.1],
 ['088/04', '088', '04', 11.2, 26201.8],
 ['088/05', '088', '05', 8.6, 27782.8],
 ['088/06', '088', '06', 9.3, 31282.5],
 ['088/07', '088', '07', 9.3, 21000.6],
 ['088/08', '088', '08', 15.1, 10110.7],
 ['088/09', '088', '09', 17.0, 10218.2],
 ['088/10', '088', '10', 14.6, 3904.2],
 ['088/11', '088', '11', 12.6, 3044.0],
 ['088/12', '088', '12', 13.5, 1041.3],
 ['089/01', '089', '01', 17.2, 831.3],
 ['089/02', '089', '02', 14.1, 3084.5],
 ['089/03', '089', '03', 18.6, 3697.6],
 ['089/04', '089', '04', 16.9, 20886.0],
 ['089/05', '089', '05', 12.4, 27153.0],
 ['089/06', '089', '06', 6.4, 40697.7],
 ['089/07', '089', '07', 10.2, 20844.9],
 ['089/08', '089', '08', 12.3, 11012.4],
 ['089/09', '089', '09', 12.5, 9826.8],
 ['089/10', '089', '10', 18.9, 2823.4],
 ['089/11', '089', '11', 13.5, 2265.5],
 ['089/12', '089', '12', 19.1, 264.7],
 ['090/01', '090', '01', 18.8, 607.4],
 ['090/02', '090', '02', 17.5, 4559.5],
 ['090/03', '090', '03', 11.9, 11706.7],
 ['090/04', '090', '04', 6.7, 32992.0],
 ['090/05', '090', '05', 9.0, 20068.0],
 ['090/06', '090', '06', 12.1, 19941.4],
 ['090/07', '090', '07', 11.6, 16509.2],
 ['090/08', '090', '08', 15.6, 12757.6],
 ['090/09', '090', '09', 10.8, 10386.1],
 ['090/10', '090', '10', 12.2, 1090.3],
 ['090/11', '090', '11', 12.5, 1645.5],
 ['090/12', '090', '12', 9.0, 863.7],
 ['091/01', '091', '01', 6.2, 564.2],
 ['091/02', '091', '02', 9.0, 2255.8],
 ['091/03', '091', '03', 13.2, 13555.7],
 ['091/04', '091', '04', 9.3, 18712.6],
 ['091/05', '091', '05', 7.1, 26320.3],
 ['091/06', '091', '06', 10.2, 20719.0],
 ['091/07', '091', '07', 12.2, 8663.5],
 ['091/08', '091', '08', 7.8, 16486.0],
 ['091/09', '091', '09', 7.4, 6717.7],
 ['091/10', '091', '10', 14.4, 2864.9],
 ['091/11', '091', '11', 14.1, 1717.9],
 ['091/12', '091', '12', 7.6, 155.8],
 ['092/01', '092', '01', 10.1, 367.0],
 ['092/02', '092', '02', 15.3, 2838.1],
 ['092/03', '092', '03', 13.2, 9950.0],
 ['092/04', '092', '04', 11.2, 11269.2],
 ['092/05', '092', '05', 10.6, 12374.0],
 ['092/06', '092', '06', 7.8, 13329.4],
 ['092/07', '092', '07', 13.1, 9056.1],
 ['092/08', '092', '08', 6.8, 18217.1],
 ['092/09', '092', '09', 10.6, 7692.1],
 ['092/10', '092', '10', 11.4, 3751.9],
 ['092/11', '092', '11', 11.4, 2243.0],
 ['092/12', '092', '12', 10.4, 672.0],
 ['093/01', '093', '01', 3.7, 764.5],
 ['093/02', '093', '02', 27.0, 2395.3],
 ['093/03', '093', '03', 21.2, 4042.1],
 ['093/04', '093', '04', 8.9, 16789.8],
 ['093/05', '093', '05', 7.7, 17554.8],
 ['093/06', '093', '06', 8.8, 15250.2],
 ['093/07', '093', '07', 14.5, 7967.1],
 ['093/08', '093', '08', 17.8, 8603.0],
 ['093/09', '093', '09', 6.4, 13027.3],
 ['093/10', '093', '10', 9.0, 3637.6],
 ['093/11', '093', '11', 7.2, 5255.8],
 ['093/12', '093', '12', 10.8, 898.5],
 ['094/01', '094', '01', 10.8, 898.5],
 ['094/02', '094', '02', 22.9, 546.6],
 ['094/03', '094', '03', 14.5, 2514.6],
 ['094/04', '094', '04', 24.1, 2657.9],
 ['094/05', '094', '05', 13.8, 11637.9],
 ['094/06', '094', '06', 16.1, 8107.4],
 ['094/07', '094', '07', 25.6, 6337.9],
 ['094/08', '094', '08', 22.2, 2593.5],
 ['094/09', '094', '09', 16.2, 3094.8],
 ['094/10', '094', '10', 19.2, 3539.0],
 ['094/11', '094', '11', 16.5, 3874.9],
 ['094/12', '094', '12', 10.7, 720.8],
 ['095/01', '095', '01', 19.1, 569.0],
 ['095/02', '095', '02', 6.5, 119.0],
 ['095/03', '095', '03', 16.9, 4440.0],
 ['095/04', '095', '04', 14.3, 5503.1],
 ['095/05', '095', '05', 10.7, 13249.4],
 ['095/06', '095', '06', 14.5, 7811.1],
 ['095/07', '095', '07', 16.8, 9860.7],
 ['095/08', '095', '08', 13.1, 14548.4],
 ['095/09', '095', '09', 13.4, 12865.9],
 ['095/10', '095', '10', 11.7, 7877.5],
 ['095/11', '095', '11', 10.8, 4304.7],
 ['095/12', '095', '12', 7.7, 137.0],
 ['096/01', '096', '01', 9.4, 360.6],
 ['096/02', '096', '02', 10.7, 1067.3],
 ['096/03', '096', '03', 12.5, 11570.8],
 ['096/04', '096', '04', 10.6, 20102.6],
 ['096/05', '096', '05', 11.3, 16160.7],
 ['096/06', '096', '06', 8.9, 15098.4],
 ['096/07', '096', '07', 10.5, 20654.6],
 ['096/08', '096', '08', 9.4, 22768.1],
 ['096/09', '096', '09', 15.8, 2285.6],
 ['096/10', '096', '10', 12.3, 1312.4],
 ['096/11', '096', '11', 9.5, 1263.4],
 ['096/12', '096', '12', 7.6, 1729.4],
 ['097/01', '097', '01', 12.4, 89.0],
 ['097/02', '097', '02', 16.2, 776.4],
 ['097/03', '097', '03', 15.0, 2106.5],
 ['097/04', '097', '04', 15.9, 11836.5],
 ['097/05', '097', '05', 10.3, 10997.3],
 ['097/06', '097', '06', 11.5, 16514.7],
 ['097/07', '097', '07', 18.9, 9278.8],
 ['097/08', '097', '08', 20.2, 4492.7],
 ['097/09', '097', '09', 13.4, 7584.1],
 ['097/10', '097', '10', 17.6, 3692.9],
 ['097/11', '097', '11', 13.6, 3763.7],
 ['097/12', '097', '12', 11.2, 1883.9],
 ['098/01', '098', '01', 6.1, 618.8],
 ['098/02', '098', '02', 21.9, 2292.6],
 ['098/03', '098', '03', 14.5, 8075.4],
 ['098/04', '098', '04', 8.0, 16616.3],
 ['098/05', '098', '05', 14.0, 13574.4],
 ['098/06', '098', '06', 10.6, 16965.8],
 ['098/07', '098', '07', 13.9, 15140.2],
 ['098/08', '098', '08', 15.8, 6017.8],
 ['098/09', '098', '09', 30.6, 1164.1],
 ['098/10', '098', '10', 13.6, 7666.4],
 ['098/11', '098', '11', 10.0, 9247.5],
 ['098/12', '098', '12', 12.0, 3076.7],
 ['099/01', '099', '01', 12.0, 3076.7],
 ['099/02', '099', '02', 19.1, 4515.0],
 ['099/03', '099', '03', 18.0, 7309.4],
 ['099/04', '099', '04', 12.9, 13768.1],
 ['099/05', '099', '05', 11.3, 8346.8],
 ['099/06', '099', '06', 7.0, 17491.1],
 ['099/07', '099', '07', 14.3, 16850.8],
 ['099/08', '099', '08', 13.5, 20401.1],
 ['099/09', '099', '09', 11.3, 9740.7],
 ['099/10', '099', '10', 22.4, 1689.1],
 ['099/11', '099', '11', 14.0, 3351.6],
 ['099/12', '099', '12', 15.9, 629.2],
 ['100/01', '100', '01', 7.4, 594.4],
 ['100/02', '100', '02', 7.3, 331.0],
 ['100/03', '100', '03', 18.3, 5025.5],
 ['100/04', '100', '04', 14.3, 19399.2],
 ['100/05', '100', '05', 13.8, 18156.8],
 ['100/06', '100', '06', 15.0, 19423.4],
 ['100/07', '100', '07', 13.0, 21109.6],
 ['100/08', '100', '08', 12.6, 21348.7],
 ['100/09', '100', '09', 15.7, 7708.3],
 ['100/10', '100', '10', 12.8, 6265.0],
 ['100/11', '100', '11', 11.0, 3979.3],
 ['100/12', '100', '12', 11.0, 3979.3],
 ['101/01', '101', '01', 8.4, 256.5],
 ['101/02', '101', '02', 8.4, 256.5],
 ['101/03', '101', '03', 19.1, 5203.4],
 ['101/04', '101', '04', 13.8, 18445.4],
 ['101/05', '101', '05', 12.2, 19121.7],
 ['101/06', '101', '06', 12.7, 17567.2],
 ['101/07', '101', '07', 31.9, 8993.1],
 ['101/08', '101', '08', 17.0, 14215.4],
 ['101/09', '101', '09', 19.2, 8451.5],
 ['101/10', '101', '10', 13.2, 7919.8],
 ['101/11', '101', '11', 14.6, 6532.2],
 ['101/12', '101', '12', 14.0, 1213.5],
 ['102/01', '102', '01', 8.5, 49.7],
 ['102/02', '102', '02', 19.4, 2219.1],
 ['102/03', '102', '03', 15.6, 8673.3],
 ['102/04', '102', '04', 9.1, 12401.2],
 ['102/05', '102', '05', 12.6, 11456.9],
 ['102/06', '102', '06', 18.7, 15055.0],
 ['102/07', '102', '07', 11.7, 21184.1],
 ['102/08', '102', '08', 17.0, 17171.8],
 ['102/09', '102', '09', 22.4, 6033.7],
 ['102/10', '102', '10', 18.2, 7355.1],
 ['102/11', '102', '11', 11.1, 4187.4],
 ['102/12', '102', '12', 11.4, 1235.6],
 ['103/01', '103', '01', 12.0, 144.0],
 ['103/02', '103', '02', 24.6, 444.0],
 ['103/03', '103', '03', 18.9, 5013.5],
 ['103/04', '103', '04', 15.9, 16950.1],
 ['103/05', '103', '05', 13.5, 12580.7],
 ['103/06', '103', '06', 12.0, 10160.8],
 ['103/07', '103', '07', 13.5, 19492.0],
 ['103/08', '103', '08', 16.1, 17326.8],
 ['103/09', '103', '09', 19.2, 11914.4],
 ['103/10', '103', '10', 17.7, 4673.4],
 ['103/11', '103', '11', 15.8, 2260.3],
 ['103/12', '103', '12', 13.0, 949.4],
 ['104/01', '104', '01', 11.8, 163.6],
 ['104/02', '104', '02', 22.0, 99.0],
 ['104/03', '104', '03', 12.7, 8660.6],
 ['104/04', '104', '04', 11.1, 20036.3],
 ['104/05', '104', '05', 13.3, 14946.4],
 ['104/06', '104', '06', 16.3, 14622.2],
 ['104/07', '104', '07', 11.2, 27651.4],
 ['104/08', '104', '08', 10.3, 30799.0],
 ['104/09', '104', '09', 23.0, 3426.1],
 ['104/10', '104', '10', 15.4, 5130.4],
 ['104/11', '104', '11', 12.4, 3911.4],
 ['104/12', '104', '12', 11.0, 1135.7],
 ['105/01', '105', '01', 7.5, 982.5],
 ['105/02', '105', '02', 17.3, 972.0],
 ['105/03', '105', '03', 16.6, 5449.9],
 ['105/04', '105', '04', 22.4, 9563.7],
 ['105/05', '105', '05', 26.3, 14663.3],
 ['105/06', '105', '06', 15.1, 21902.0],
 ['105/07', '105', '07', 26.5, 14199.0],
 ['105/08', '105', '08', 22.8, 24319.6],
 ['105/09', '105', '09', 13.9, 13089.0],
 ['105/10', '105', '10', 15.6, 1695.3],
 ['105/11', '105', '11', 25.2, 512.7],
 ['105/12', '105', '12', 18.3, 1546.2],
 ['106/01', '106', '01', 19.8, 360.2],
 ['106/02', '106', '02', 14.1, 6585.4],
 ['106/03', '106', '03', 12.8, 5739.9],
 ['106/04', '106', '04', 13.5, 11709.0],
 ['106/05', '106', '05', 17.8, 9365.4],
 ['106/06', '106', '06', 11.7, 14625.3],
 ['106/07', '106', '07', 20.0, 14697.1],
 ['106/08', '106', '08', 12.9, 29048.7],
 ['106/09', '106', '09', 16.6, 15533.2],
 ['106/10', '106', '10', 13.3, 11279.6],
 ['106/11', '106', '11', 14.0, 2430.6],
 ['106/12', '106', '12', 10.6, 1268.6],
 ['107/01', '107', '01', 10.6, 1268.6],
 ['107/02', '107', '02', 10.6, 1268.6],
 ['107/03', '107', '03', 23.3, 8831.8],
 ['107/04', '107', '04', 10.8, 38365.0],
 ['107/05', '107', '05', 12.2, 19975.7],
 ['107/06', '107', '06', 13.8, 14960.2],
 ['107/07', '107', '07', 17.6, 14343.2],
 ['107/08', '107', '08', 12.7, 21482.3],
 ['107/09', '107', '09', 11.5, 10128.6],
 ['107/10', '107', '10', 12.7, 4805.1],
 ['107/11', '107', '11', 8.5, 4665.5],
 ['107/12', '107', '12', 8.7, 821.4],
 ['108/01', '108', '01', 8.7, 821.4],
 ['108/02', '108', '02', 11.3, 5553.3],
 ['108/03', '108', '03', 8.9, 9625.9],
 ['108/04', '108', '04', 14.9, 13723.7],
 ['108/05', '108', '05', 15.3, 12717.2],
 ['108/06', '108', '06', 16.1, 11395.4],
 ['108/07', '108', '07', 14.4, 17597.9],
 ['108/08', '108', '08', 14.8, 15618.3],
 ['108/09', '108', '09', 22.8, 3924.3],
 ['108/10', '108', '10', 16.9, 8380.7],
 ['108/11', '108', '11', 15.1, 981.7],
 ['108/12', '108', '12', 14.3, 1166.3]]

In [72]:
df_new = pd.DataFrame(new_df,columns=['date','year','month','price','volumn'])
df_new.to_csv('month_data.csv',encoding='utf-8-sig')